# Dependencies
gems: [jekyll-paginate, jekyll-gist]

kramdown:
  input: GFM
  syntax_highlighter: rouge

# Permalinks
permalink:        pretty

# Setup
title:            Rust
tagline:          'My Blog'
description:      'Winter is coming.'
url:              http://dacainiao.github.io
baseurl:          /

author:
  name:           'Jason Chi'
  url:            https://twitter.com/jsonchi

jekyll-paginate:         5
