# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Rust
tagline:          'My Blog'
description:      'Winter is coming.'
url:              http://dacainiao.github.io
baseurl:          /

author:
  name:           'Jason Chi'
  url:            https://twitter.com/jsonchi

paginate:         5
